apiVersion: apps/v1
kind: Deployment
metadata:
  name: briefcase-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: briefcase-auth-1
        image: soumyaai/briefcase-auth-1
        #imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: briefcase-entrypoint
  namespace: default
spec:
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort

